In [1]:
%matplotlib nbagg

In [2]:
import hyperspy.api as hs
import EELS.EELS as eels
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve

In [3]:
positions = [[0.3333333333333357,  0.6666666666666643,  0.9996814330926364],
             [0.6666666666666643,  0.3333333333333357,  0.4996814330926362],
             [0.3333333333333357,  0.6666666666666643,  0.3787615522102606],
             [0.6666666666666643,  0.3333333333333357,  0.8787615522102604]]

numbers = [8, 8, 30, 30]

atoms = []
for i, position in enumerate(positions):
    atoms.append(eels.Atom(numbers[i],position))
atoms

In [4]:
lattice = np.array([[ 3.2871687359128612, 0.0000000000000000, 0.0000000000000000],
                    [-1.6435843679564306, 2.8467716318265182, 0.0000000000000000],
                    [ 0.0000000000000000, 0.0000000000000000, 5.3045771064003047]])

cell = eels.Cell(lattice = lattice,
                atoms=atoms)


In [5]:
model = eels.ModelSystem(cell=cell)


model.meshgrid(pointDensity=np.array([41, 41, 41]))

model.addParabolicBand(energy_offset=0.0, effective_mass=np.array([-2.45,  -2.45, -2.45]), k_center=np.array([0, 0, 0]))
model.addParabolicBand(energy_offset=3.3, effective_mass=np.array([ 0.29,  0.29,  0.25]), k_center=np.array([0, 0, 0]))

energyBins = np.linspace(3,5,100)

print(model.diffractionGrid()[1])

print(model.cell.brillouinZone)
model.spaceGroup()

[63 73 39]
[[ 1.91142768  1.10356328 -0.        ]
 [ 0.          2.20712657  0.        ]
 [ 0.         -0.          1.18448374]]


'P6_3mc (186)'

In [6]:
s = model.calculateScatteringCrossSection(energyBins, fermiEnergy=1.65, temperature=0)

s.metadata['General']['authors'] = "Sindre R. Bilden"
s.metadata['General']['name'] = "Reference"
s.metadata['General']['notes'] = "ZnO model"
s.metadata['General']['title'] = "Reference"


s.save('../Results/Cecilie/ZnO/41/T0F%.2f.hspy' %(s.metadata['Sample']['system']['fermiEnergy']))

CCD:
[ 1.91142768  2.20712657  1.18448374] [63 73 39]


ERROR:hyperspy.io_plugins.hspy:The hdf5 writer could not write the following information in the file: 0 : <EELS.EELS.Band object at 0x7fa078ef6198>
Traceback (most recent call last):
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/hyperspy/io_plugins/hspy.py", line 477, in dict2hdfgroup
    group.attrs[key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1607, in h5py.h5t.py_cr

In [7]:
s = model.calculateScatteringCrossSection(energyBins, fermiEnergy=3.6, temperature=0)

s.metadata['General']['authors'] = "Sindre R. Bilden"
s.metadata['General']['name'] = "T=0K Ef=3.6eV"
s.metadata['General']['notes'] = "ZnO model"
s.metadata['General']['title'] = "T=0K Ef=3.6eV"
s.save('../Results/Cecilie/ZnO/41/T0F%.2f.hspy' %(s.metadata['Sample']['system']['fermiEnergy']))

CCD:
[ 1.91142768  2.20712657  1.18448374] [63 73 39]


ERROR:hyperspy.io_plugins.hspy:The hdf5 writer could not write the following information in the file: 0 : <EELS.EELS.Band object at 0x7fa0c4f4a160>
Traceback (most recent call last):
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/hyperspy/io_plugins/hspy.py", line 477, in dict2hdfgroup
    group.attrs[key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1607, in h5py.h5t.py_cr

In [8]:
s = model.calculateScatteringCrossSection(energyBins, fermiEnergy=3.6, temperature=300)

s.metadata['General']['authors'] = "Sindre R. Bilden"
s.metadata['General']['name'] = "T=300K Ef=3.6eV"
s.metadata['General']['notes'] = "ZnO model"
s.metadata['General']['title'] = "T=300K Ef=3.6eV"
s.save('../Results/Cecilie/ZnO/41/T300F%.2f.hspy' %(s.metadata['Sample']['system']['fermiEnergy']))

CCD:
[ 1.91142768  2.20712657  1.18448374] [63 73 39]


ERROR:hyperspy.io_plugins.hspy:The hdf5 writer could not write the following information in the file: 0 : <EELS.EELS.Band object at 0x7fa07d03b438>
Traceback (most recent call last):
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/hyperspy/io_plugins/hspy.py", line 477, in dict2hdfgroup
    group.attrs[key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/sindrerb/anaconda3/envs/hySpy2/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1607, in h5py.h5t.py_cr